### PR TITLE
404 updated with link to old website archive and search bar

### PR DESCRIPTION
**Pull request by BobbyRBruce**
This should be merged once https://gem5.atlassian.net/browse/GEM5-245 is complete. GEM5-245 currently blocks this.

### CODE REVIEW

**Comment by powerjg** [comment]
You might need to add `.html` to the end of the "old" URL to get this to work.

E.g., http://old.gem5.org/Repository.html

**Comment by BobbyRBruce** [comment]
Fixed that small error.

**Comment by powerjg** [comment]
I assume you tested this locally?

**Comment by BobbyRBruce** [comment]
Yes, I tested it locally. It's good.

**Comment by BobbyRBruce** [comment]
(I'll triple check on the new.gem5.org site once it's recompiled)

**Pull request merged**
