### PR TITLE
Add mem docs

### PR DESCRIPTION
**Pull request by powerjg**
Work in progress. Working on https://gem5.atlassian.net/projects/GEM5/issues/GEM5-158

### CODE REVIEW

**Comment by powerjg** [comment]
I don't think this should have a deep review for two reasons:
1. It will take a lot of someone's time
2. I don't want to fix lots of little things

We can fix things in the future as we find errors. 

One thing we might want to do is mark pages with "may be out of date" so we know what we need to go back and do.

One thing I would like feedback on is the directory structure.

Finally, I think much of this needs to be added to `_data/documentation.yml`, but I think we should automatically do it, not manually.

**Comment by powerjg** [comment]
I added everything to the `_data/documentation` file. However, it doesn't work as expected. I thought I would see the hierarchy show up on the left column, but it's not there. Not sure why.

**Comment by powerjg** [comment]
Yeah, that's definitely the case. I don't know how to fix it, though.

I'd appreciate it if someone else would dig into this. :)

**Comment by BobbyRBruce** [comment]
I'll take a look and see if I can figure it out

**Comment by BobbyRBruce** [comment]
I've fixed the hierarchy issues. Still a lot of broken links and some missing images, though I believe you are aware of these and want to have them as a TODO for later? If so, I'm happy for this to be merged.

**Pull request merged**
