### PR TITLE
Add back events link

### PR DESCRIPTION
**Pull request by powerjg**
Signed-off-by: Jason Lowe-Power <jason@lowepower.com>

### CODE REVIEW

**Comment by powerjg** [comment]
Hey @BobbyRBruce Could you take a look at this?

The code review doesn't *really* matter, but I guess it's better to have two sets of eyes on things :).

**Comment by geneticimprovementofsoftware** [comment]
@powerjg Looking good!. I only picked up on three small problems:

`_pages/events/dist-gem5.md` @ line 67 contains a reference to "Packet-forwarding-highlevel.png". This appears to be a dead line.

The "Documentation" link on the websites footer is broken.

Ditto the "Mailing Lists" link.

**Comment by BobbyRBruce** [comment]
@powerjg Looking good!. I only picked up on three small problems:

_pages/events/dist-gem5.md @ line 67 contains a reference to "Packet-forwarding-highlevel.png". This appears to be a dead line.

The "Documentation" link on the websites footer is broken.

Ditto the "Mailing Lists" link.

**Comment by powerjg** [comment]
I'll let you (@BobbyRBruce) fix the mailing list link since you're going to add that page :). Then, I'll fix the broken documentation link in another PR (probably with a direct push...)

**Comment by powerjg** [comment]
I updated the links I could, and left the others. Thanks for the review!

**Pull request merged**
