### PR TITLE
website: ISCA 2024 update schedule

### PR DESCRIPTION
**Pull request by ivanaamit**
This PR adds break information for the workshop.

### CODE REVIEW

**Comment by mattsinc** [comment]
thanks for doing this @ivanaamit !  Looking now

**Review by mattsinc — APPROVED** [review]
perfect, thanks @ivanaamit !

**Review by powerjg — APPROVED** [review]
Feel free to push to get arount the precommit issue

**Review by abmerop — COMMENTED** [review]
Look good for our section

**Pull request merged**
