### PR TITLE
Fixed documentation (fixed hierarchy).

### PR DESCRIPTION
**Pull request by BobbyRBruce**
This puts all the general docs under "gem5 documentation".

### CODE REVIEW

**Comment by BobbyRBruce** [comment]
I fixed the overarching problems. Have a play with it and see if you have any last minute update requests.

**Comment by powerjg** [comment]
How does this relate to #48? Is this a replacement for #48?

**Comment by powerjg** [comment]
This looks great! A couple of comments :)

- I believe this and #48 need to be integrated. I'm not sure the best way to do that. We can probably drop some of the index.md's from #48 when doing the integration as I think the current layout is great.
- There's a few broken links (e.g., Development is missing a leading `/` and checkpoints and m5ops are broken--this might be due to capitalization)
- Let's move gem5 101 under Learning gem5
- the Doxygen should be a top level link in the drop down menu instead of under "documentation"
- There doesn't seem to be a way to get to `/documentation/`. It would be good if the documentation link in the drop down menu took you there (not sure if this is easy, hard, or impossible)

**Comment by BobbyRBruce** [comment]
Ok. I'll fix these things this morning

**Comment by BobbyRBruce** [comment]
Ok Jason. This is all done. I'm happy with things as they are. All the broken links I could find have been fixed. There's also now a landing page for documentation.

**Pull request merged**
